### PR TITLE
Feature/room expansion

### PR DESCRIPTION
**Pull request by JohannDoell**
This is a huge expansion of the 30x30 room pool. Each has two door slots.

### CODE REVIEW

**Review by ConnorCooke — APPROVED** [review]

**Review by ads567 — APPROVED** [review]

**Comment by DanielMcCoshen** [comment]
load the room entries in game.py and and roomlist.cs before merging maybe?

**Review by DanielMcCoshen — CHANGES_REQUESTED** [review]
as mentioned in my previous comment, (I didnt realize I had to include one here) maybe it could be a good idea to populate the room entries in the server and the game before this is merged. make sure to pull the filtering changes from devel if this is going to be done

**Comment by JohannDoell** [comment]
All right. Git is telling me this branch is up to date with devel, so I shan't touch it further, milord.

**Comment by JohannDoell** [comment]
All right! They are now in the server on this branch!

**Review by DanielMcCoshen — APPROVED** [review]

**Pull request merged**
